src/MyDairy.Web/Models/ErrorViewModel.cs
namespace MyDairy.Web.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

src/MyDairy.Web/Models/LoginViewModel.cs
namespace MyDairy.Web.Models;

public class LoginViewModel
{
    public string Username { get; set; }

    public string Password { get; set; }
}

src/MyDairy.Web/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MyDairy.Web.Models;
using System.Diagnostics;

namespace MyDairy.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

src/MyDairy.Web/Controllers/NotesController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using MyDairy.Service.DTOs.Notes;
using MyDairy.Service.Interfaces.Notes;

namespace MyDairy.Web.Controllers;

[Route("notes")]
public class NotesController : Controller
{
    private readonly INoteService _noteService;
    private readonly IMapper _mapper;

    public NotesController(INoteService noteService, IMapper mapper)
    {
        _noteService = noteService;
        _mapper = mapper;
    }

    public async Task<IActionResult> Index()
    {
        var notes = await _noteService.GetAllAsync();
        return View(notes);
    }

    [HttpGet("details")]
    public async Task<IActionResult> Details(long id)
    {
        var note = await _noteService.GetByIdAsync(id);
        return View(note);
    }

    [HttpGet("create")]
    public IActionResult Create(long userId)
    {
        return View(new NoteCreationDto() { UserId = userId });
    }

    [HttpPost("create")]
    public async Task<IActionResult> Create(NoteCreationDto noteDto)
    {
        var createdNote = await _noteService.CreateAsync(noteDto);
        return RedirectToAction(nameof(Details), new { id = createdNote.Id });
    }

    [HttpGet("update")]
    public async Task<IActionResult> Update(long id)
    {
        var note = await _noteService.GetByIdAsync(id);
        var mappedNote = _mapper.Map<NoteUpdateDto>(note);
        return View(mappedNote);
    }

    [HttpPost("update")]
    public async Task<IActionResult> Update(NoteUpdateDto noteDto)
    {
        var updatedNote = await _noteService.UpdateAsync(noteDto);
        return RedirectToAction("details", "notes", new { id = updatedNote.Id });
    }

    [HttpPost("delete/{id}")]
    public async Task<IActionResult> Delete(long id)
    {
        var note = await _noteService.GetByIdAsync(id);
        await _noteService.DeleteAsync(id);
        return RedirectToAction("getbyid", "users", new { id = note.User.Id });
    }
}

src/MyDairy.Web/Controllers/UsersController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using MyDairy.Service.DTOs.Attachment;
using MyDairy.Service.DTOs.Users;
using MyDairy.Service.Interfaces.Users;
using MyDairy.Web.Models;

namespace MyDairy.Web.Controllers;

[Route("users")]
public class UsersController : Controller
{
    private readonly IUserService _userService;
    private readonly IMapper _mapper;

    public UsersController(IUserService userService, IMapper mapper)
    {
        _mapper = mapper;
        _userService = userService;
    }

    [HttpGet("create")]
    public async Task<IActionResult> Create()
    {
        return View(new UserCreationDto());
    }

    [HttpPost("create")]
    public async Task<IActionResult> Create(UserCreationDto userDto)
    {
        var newUser = await _userService.CreateAsync(userDto);
        return RedirectToAction("getbyid", new { newUser.Id });
    }

    [HttpGet("update")]
    public async Task<IActionResult> Update(long Id)
    {
        var user = await _userService.GetByIdAsync(Id);
        var mappedUser = _mapper.Map<UserUpdateDto>(user);
        return View(mappedUser);
    }

    [HttpPost("update")]
    public async Task<IActionResult> Update(UserUpdateDto userDto)
    {
        var updatedUser = await _userService.UpdateAsync(userDto);
        return RedirectToAction("GetById", new { id = updatedUser.Id });
    }

    [HttpPost("upload-photo")]
    public async Task<IActionResult> UploadAvatar(long id, [FromForm] AttachmentCreationDto dto)
    {
        await _userService.UploadPhotoAsync(id, dto);

        return RedirectToAction(nameof(GetById), new { id });
    }

    [HttpPost("delete/{id}")]
    public async Task<IActionResult> Delete(long id)
    {
        await _userService.DeleteAsync(id);
        return RedirectToAction("index", "users");
    }

    [HttpGet("getbyid/{id}")]
    public async Task<IActionResult> GetById(long id)
    {
        var user = await _userService.GetByIdAsync(id);
        return View(user);
    }

    [HttpGet("getall")]
    [ActionName("index")]
    public async Task<IActionResult> GetAll()
    {
        var users = await _userService.GetAllAsync();
        return View(users);
    }

    [HttpGet("search")]
    public async Task<IActionResult> SearchByName(string name)
    {
        var users = await _userService.GetAllByNameAsync(name);
        return View(users);
    }

    [HttpGet("searchByUsername")]
    public async Task<IActionResult> SearchByUsername(string username)
    {
        var users = await _userService.GetAllByUsernameAsync(username);
        return View(users);
    }

    [HttpGet("login")]
    public async Task<IActionResult> Login()
    {
        var model = new LoginViewModel();
        return View(model);
    }

    [HttpPost("login")]
    public async Task<IActionResult> Login(LoginViewModel loginView)
    {
        var flag = await _userService.CheckCredentialsAsync(loginView.Username,loginView.Password);
        if (flag)
        {
            var user = (await _userService.GetAllByUsernameAsync(loginView.Username)).FirstOrDefault();
            if(user is not null)
                return RedirectToAction("getbyid", new { id = user.Id});
        }

        return RedirectToAction("login");
    }
}

src/MyDairy.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome to my first MVC project</h1>
</div>

src/MyDairy.Web/Views/Notes/Create.cshtml
@model MyDairy.Service.DTOs.Notes.NoteCreationDto

@{
    ViewData["Title"] = "Create New Note";
}

<div class="container mt-5">
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Create New Note</h5>
                    <form asp-controller="Notes" asp-action="Create" method="post">
                        <input type="hidden" asp-for="UserId" value="@Model.UserId" />
                        <div class="form-group">
                            <label asp-for="Title">Title</label>
                            <input type="text" class="form-control" id="Title" name="Title" required>
                        </div>
                        <div class="form-group">
                            <label asp-for="Description">Description</label>
                            <textarea class="form-control" id="Description" name="Description" rows="3" required></textarea>
                        </div>
                        <p></p>
                        <button type="submit" class="btn btn-primary">Create Note</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

src/MyDairy.Web/Views/Notes/Details.cshtml
@model MyDairy.Service.DTOs.Notes.NoteResultDto

@{
    ViewData["Title"] = "Note Details";
}

<div class="container mt-5">
    <div class="card">
        <div class="card-header">
            <h5 class="card-title">@Model.Title</h5>
        </div>
        <div class="card-body">
            <p class="card-text">@Model.Description</p>
            @if (Model.Attachment != null)
            {
                <img src="~/images/@Model.Attachment.Name" class="note-image" alt="Note Image">
            }
        </div>
        <div class="card-footer d-flex justify-content-between">

            <a asp-action="Update" asp-route-id="@Model.Id" class="btn btn-primary ml-auto">Edit Note</a>

            <form asp-controller="notes" asp-action="delete" asp-route-id="@Model.Id" method="post"
                  onclick="return confirm('Are you sure you want to delete this note?')">
                <button type="submit" class="btn btn-danger">Delete Note</button>
            </form>
        </div>

    </div>
</div>
<div class="back-button">
    <a asp-controller="users" asp-action="getbyid" asp-route-id="@Model.User.Id" class="btn btn-secondary">Back</a>
</div>

<style>
    .note-image {
        max-width: 100%;
        height: auto;
        margin-top: 10px;
    }

    .back-button {
        position: fixed;
        bottom: 20px;
        right: 20px;
        margin-right: 9.5%
    }
</style>

src/MyDairy.Web/Views/Notes/Update.cshtml
@model MyDairy.Service.DTOs.Notes.NoteUpdateDto

@{
    ViewData["Title"] = "Update Note";
}

<div class="container mt-5">
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Create New Note</h5>
                    <form asp-controller="Notes" asp-action="Update" method="post">
                        <input type="hidden" asp-for="UserId" value="@Model.UserId" />
                        <input type="hidden" asp-for="Id" value="@Model.Id" />
                        <div class="form-group">
                            <label asp-for="Title">Title</label>
                            <input type="text" class="form-control" id="Title" value="@Model.Title" name="Title" required>
                        </div>
                        <div class="form-group">
                            <label asp-for="Description">Description</label>
                            <textarea class="form-control" id="Description" name="Description" rows="3" required>@Model.Description</textarea>
                        </div>
                        <p></p>
                        <button type="submit" class="btn btn-primary">Update Note</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

src/MyDairy.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MyDairy.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MyDairy.Web.styles.css" asp-append-version="true" />
</head>
<body style="background-color:#FFF0F5">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow" style="margin:0%">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="users" asp-action="Index">MyDairy</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="users" asp-action="create">Register</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="users" asp-action="login">Login</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container-fluid">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

src/MyDairy.Web/Views/Users/Create.cshtml
<h1>Register</h1>

@{
    ViewData["Title"] = "My Dairy Sign up";
}

@using MyDairy.Service.DTOs.Users;
@model UserCreationDto

<form asp-controller="Users" asp-action="Create" method="post">
    <div class="form-group">
        <label asp-for="Firstname">Firstname</label>
        <input type="text" class="form-control" id="Firstname" name="Firstname" placeholder="Enter your name" maxlength="25" required>
    </div>
    <div class="form-group">
        <label asp-for="Lastname">Lastname</label>
        <input type="text" class="form-control" id="Lastname" name="Lastname" placeholder="Enter your surname" maxlength="25" required>
    </div>
    <div class="form-group">
        <label asp-for="Username">Username</label>
        <input type="text" class="form-control" id="Username" name="Username" placeholder="Enter new username" maxlength="25" required>
    </div>
    <div class="form-group">
        <label asp-for="Password">Password</label>
        <input type="password" class="form-control" id="Password" name="Password" placeholder="Enter new Password" required>
    </div>
    <p></p>
    <button type="submit" class="btn btn-primary">Register</button>
</form>

src/MyDairy.Web/Views/Users/GetAll.cshtml
@using MyDairy.Service.DTOs.Users;
@model IEnumerable<UserResultDto>

@{
    ViewData["Title"] = "GetAll";
}

<h1>All users</h1>

<div class="row">
    @foreach (var user in Model)
    {
        <div class="col-md-4 mb-4">
            <div class="card">
                <img id="profile_img" src="~/images/@user.Attachment.Name" class="card-img-top" alt="User Avatar">
                <div class="card-body">
                    <h5 class="card-title">@user.Firstname @user.Lastname</h5>
                    <p class="card-text">@user.Username</p>
                    <a href="@Url.Action("GetById", "Users", new { id = user.Id })" class="btn btn-primary">View Profile</a>
                </div>
            </div>
        </div>
    }
</div>

src/MyDairy.Web/Views/Users/GetById.cshtml
@using MyDairy.Service.DTOs.Users;
@using MyDairy.Service.DTOs.Notes;
@model UserResultDto

@{
    ViewData["Title"] = "Your Profile";
}

<div class="container mt-5">
    <div class="row">
        <!-- Left Side: Profile Information -->
        <div class="col-md-4">
            <div class="card">
                <div class="profile-image-container">
                    @if (@Model.Attachment is null)
                    {
                        <img class="card-img-top profile-image" src="~/images/profile_image.jpg" alt="User Avatar">
                    }
                    else
                    {
                        <img src="~/images/@Model.Attachment.Name" class="card-img-top profile-image" alt="Profile Image">
                    }
                </div>
                <div class="card-body">
                    <p class="card-text">@Model.Username</p>
                    <p class="card-text">@Model.Firstname @Model.Lastname</p>

                    <form asp-action="UploadAvatar" asp-route-id="@Model.Id" method="post" enctype="multipart/form-data">
                        <div class="form-group">
                            <label for="avatar">Avatar Image</label>
                            <p></p>
                            <input type="file" class="form-control-file" name="dto.File" id="avatar" required>
                        </div>
                        <p></p>
                        <button type="submit" class="btn btn-primary">Upload Photo</button>
                    </form>

                    <!-- Link to edit profile -->
                    <a asp-controller="users" asp-action="update" asp-route-id="@Model.Id" method="get" class="btn btn-secondary mt-3">Edit Profile</a>
                </div>
            </div>
        </div>

        <div class="col-md-8">
            <div class="card">
                <div class="card-body">
                    <div class="d-flex justify-content-between align-items-center mb-3">
                        <h5 class="card-title">Notes</h5>
                        <a asp-controller="Notes" asp-action="Create" asp-route-userId="@Model.Id" class="btn btn-primary">Create Note</a>
                    </div>
                    @if (Model.Notes != null && Model.Notes.Count > 0)
                    {
                        foreach (var note in Model.Notes)
                        {
                            <div class="note">
                                <h6>@note.Title</h6>
                                <p class="note-description">@note.Description.Substring(0, Math.Min(note.Description.Length, 85))...</p>
                                <p class="note-details" style="display: none;">@note.Description</p>
                                <a asp-action="details" asp-controller="notes" asp-route-id="@note.Id" class="btn btn-primary">Read more</a>
                            </div>
                        }
                    }
                    else
                    {
                        <p>No notes available.</p>
                    }
                </div>
            </div>
        </div>
    </div>
</div>
<style>
    .profile-image-container {
        text-align: center;
        padding-top: 20px;
    }

    .profile-image {
        width: 150px;
        height: 150px;
        border-radius: 50%;
        object-fit: cover;
    }

    .input-group .custom-file-input::after {
        content: "Browse";
    }

    .input-group .custom-file-input::-webkit-file-upload-button {
        visibility: hidden;
    }

    .input-group .custom-file-input::before {
        content: "Upload";
        display: inline-block;
        background: linear-gradient(top, #f9f9f9, #e3e3e3);
        border: 1px solid #999;
        border-radius: 3px;
        padding: 5px 8px;
        outline: none;
        white-space: nowrap;
        -webkit-user-select: none;
        cursor: pointer;
        text-shadow: 1px 1px #fff;
        font-weight: 700;
        font-size: 10pt;
    }

    .note {
        margin-bottom: 20px;
        padding: 10px;
        border: 1px solid #ddd;
        background-color: #f9f9f9;
    }

    .note-image {
        max-width: 100%;
        height: auto;
        margin-top: 10px;
    }
</style>

src/MyDairy.Web/Views/Users/Index.cshtml
@using MyDairy.Domain.Entities;
@using MyDairy.Service.DTOs.Users;
@model IEnumerable<UserResultDto>

@{
    ViewData["Title"] = "GetAll";
    UserResultDto currentUser = new UserResultDto();

}

<div class="main-container border border-dark w-100 h-100">
    <div class="users-container col">
        <div class="nav-bar">
            <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
            <button class="btn"><i class="fa fa-bars"></i></button>

            <div class="form-outline mb-3">
                <input type="search" class="form-control" style="margin-top:7%; margin-left:0%" id="data-search">
            </div>
        </div>
        <ul class="user-list" id="users">
            @foreach (var user in Model)
            {
                <li class="user-item" onclick="">
                    @if(user.Attachment is null)
                    {
                        <img class="user-avatar" src="~/images/profile_image.jpg" alt="User Avatar">
                    }
                    else
                    {
                        <img class="user-avatar" src="~/images/@user.Attachment.Name" alt="User Avatar">
                    }
                    <div>
                        <h5 style="padding-top:12%">@user.Firstname @user.Lastname</h5>
                        <p>@user.Username</p>
                    </div>
                </li>
            }
        </ul>
    </div>

    <div class="notes-container col-7" id="userNotes">
        <div class="col-md-8">
            <div class="card">
                <div class="card-body">

                    <div class="d-flex justify-content-between align-items-center mb-3">
                        <h5 class="card-title">Notes</h5>
                    <a asp-controller="Notes" asp-action="Create" asp-route-userId="@currentUser.Id" style="background-color:aqua" class="btn btn-primary">Create Note</a>
                    </div>
                    
                    @if (currentUser.Notes != null && currentUser.Notes.Count > 0)
                    {
                        foreach (var note in currentUser.Notes)
                        {
                            <div class="note">
                                <h6>@note.Title</h6>
                                <p class="note-description">@note.Description.Substring(0, Math.Min(note.Description.Length, 85))...</p>
                                <p class="note-details" style="display: none;">@note.Description</p>
                                <a asp-action="details" asp-controller="notes" asp-route-id="@note.Id" class="btn btn-primary">Read more</a>
                            </div>
                        }
                    }
                    else
                    {
                        <p>No notes available.</p>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

<style>

    .main-container {
        display: flex;
        position: absolute;
        width: 100%;
        left: 0;
        flex: 1;
    }

    .users-container {
        flex: 1;
        scrollbar-width:thin;
        width:50%;
        scrollbar-color: grey;
        display: flex;
        flex-direction: column;
        border-right: 1px solid #ccc;
        overflow-y:scroll;
    }

    .user-list {
        list-style: none;
        padding: 0;
        padding-left:4%;
    }

    .user-item {
        cursor: pointer;
        display: flex;
        align-items: center;
        padding: 0px;
        transition: background-color 0.3s;
    }

    .user-item:hover {
        background-color: #f2f2f2;
    }

    .user-avatar {
        width: 50px;
        height: 50px;
        border-radius: 50%;
        margin-right: 10px;
    }

    .notes-container {
        flex: 2;
        padding: 20px;
        overflow-y: auto;
    }

    .nav-bar {
        padding: 10px;
        display: flex;
        height:10%;
        justify-content: space-between;
        align-items: center;
    }

    .nav-title {
        font-size: 20px;
        margin: 0;
    }

    .btn {
        border: none; 
        color: grey; 
        padding: 12px 16px;
        font-size: 16px; 
        cursor: pointer;
    }

</style>

<script>
    const instance = new mdb.Datatable(document.getElementById('users'), @Model)

    document.getElementById('data-search').addEventListener('input', (e) => {
        instance.input - group(e.target.value);
    });
</script>

src/MyDairy.Web/Views/Users/Login.cshtml
@{
    ViewData["Title"] = "Login";
}
@model LoginViewModel

<h1>Login</h1>
<form asp-controller="Users" asp-action="login" method="post">
    <div class="form-group">
        <label asp-for="Username">Username</label>
        <input type="text" class="form-control" id="Username" name="Username" placeholder="Enter your username" required>
    </div>
    <div class="form-group">
        <label asp-for="Password">Password</label>
        <input type="password" class="form-control" id="Password" name="Password" placeholder="Enter your password" required>
    </div>
    <p></p>
    <button type="submit" class="btn btn-primary">Login</button>
</form>

src/MyDairy.Web/Views/Users/Update.cshtml
<h1>Settings</h1>

@{
    ViewData["Title"] = "Edit your profile";
}

@using MyDairy.Service.DTOs.Users;
@model UserUpdateDto

<form asp-controller="Users" asp-action="update" method="post">
    <input type="hidden" asp-for="Id" value="@Model.Id" />
    <div class="form-group">
        <label asp-for="Firstname">Firstname</label>
        <input type="text" class="form-control" id="Firstname" name="Firstname" value="@Model.Firstname" maxlength="25" required>
    </div>
    <div class="form-group">
        <label asp-for="Lastname">Lastname</label>
        <input type="text" class="form-control" id="Lastname" name="Lastname" value="@Model.Lastname" maxlength="25" required>
    </div>
    <div class="form-group">
        <label asp-for="Username">Username</label>
        <input type="text" class="form-control" id="Username" name="Username" value="@Model.Username" maxlength="25" required>
    </div>
    <p></p>
    <button type="submit" class="btn btn-primary">Save</button>
</form>

<div class="delete-button">
    <!-- Button for deleting account -->
    <form asp-controller="users" asp-action="delete" asp-route-id="@Model.Id" method="post"
                onclick="return confirm('Are you sure you want to delete Account?')">
            <button type="submit" class="btn btn-danger">Delete Account</button>
</form>
</div>

<style>
    .delete-button {
        position: fixed;
        bottom: 20px;
        right: 20px;
    }
</style>